// Static dropdown options for AboutStep

export const highestEducationOptions = [
  'Below 10th',
  '10th Pass',
  '12th Pass',
  'Diploma',
  'ITI',
  'Polytechnic',
  'Certification Course',
  'B.A',
  'B.Sc',
  'B.Com',
  'BBA',
  'BBM',
  'BCA',
  'B.Tech',
  'B.E',
  'B.Arch',
  'B.Pharm',
  'BDS',
  'MBBS',
  'LLB',
  'B.Ed',
  'BHM (Hotel Management)',
  'BFA',
  'M.A',
  'M.Sc',
  'M.Com',
  'MBA',
  'MCA',
  'M.Tech',
  'M.E',
  'M.Pharm',
  'MD',
  'MS',
  'MDS',
  'LLM',
  'M.Ed',
  'MHM',
  'Ph.D',
  'M.Phil',
  'CA',
  'CS',
  'CMA',
  'ICWA',
  'LLP Qualified',
  'Professional Degree',
  'Foreign Degree',
  'Post Doctorate',
  'Other',
  'Not Specified',
].map((v) => ({ id: v, name: v }));

export const professionOptions = [
  'Software Engineer',
  'Web Developer',
  'Mobile App Developer',
  'Data Analyst',
  'Data Scientist',
  'AI / ML Engineer',
  'DevOps Engineer',
  'QA / Test Engineer',
  'UI / UX Designer',
  'IT Support',
  'System Administrator',
  'Business Analyst',
  'Project Manager',
  'Product Manager',
  'Operations Manager',
  'HR Professional',
  'Recruiter',
  'Marketing Executive',
  'Digital Marketing Specialist',
  'Sales Executive',
  'Account Manager',
  'Customer Support Executive',
  'Chartered Accountant (CA)',
  'Company Secretary (CS)',
  'Cost Accountant (CMA)',
  'Accountant',
  'Auditor',
  'Financial Analyst',
  'Banker',
  'Investment Advisor',
  'Insurance Professional',
  'Government Employee',
  'Civil Services (IAS/IPS/IFS)',
  'PSU Employee',
  'Defense Services',
  'Police',
  'Railway Employee',
  'Public Sector Bank Employee',
  'Teacher (Government)',
  'Clerk',
  'Teacher',
  'Professor / Lecturer',
  'Research Scholar',
  'Tutor',
  'Academic Counselor',
  'Doctor',
  'Surgeon',
  'Dentist',
  'Ayurvedic Doctor',
  'Homeopathic Doctor',
  'Physiotherapist',
  'Nurse',
  'Pharmacist',
  'Medical Technician',
  'Psychologist',
  'Mechanical Engineer',
  'Civil Engineer',
  'Electrical Engineer',
  'Electronics Engineer',
  'Chemical Engineer',
  'Production Engineer',
  'Business Owner',
  'Entrepreneur',
  'Startup Founder',
  'Self Employed',
  'Trader',
  'Wholesaler',
  'Retailer',
  'Distributor',
  'Franchise Owner',
  'Lawyer',
  'Advocate',
  'Legal Advisor',
  'Judge',
  'Graphic Designer',
  'Fashion Designer',
  'Interior Designer',
  'Photographer',
  'Videographer',
  'Content Writer',
  'Journalist',
  'Media Professional',
  'Hotel Manager',
  'Restaurant Owner',
  'Chef',
  'Catering Professional',
  'Travel Consultant',
  'Tour Operator',
  'Factory Supervisor',
  'Production Manager',
  'Quality Inspector',
  'Machine Operator',
  'Technician',
  'Electrician',
  'Plumber',
  'Carpenter',
  'Supply Chain Manager',
  'Logistics Coordinator',
  'Warehouse Manager',
  'Transport Business',
  'Fleet Manager',
  'Farmer',
  'Agricultural Business',
  'Dairy Farmer',
  'Agro Consultant',
  'Army Personnel',
  'Navy Personnel',
  'Air Force Personnel',
  'Security Officer',
  'Artist',
  'Musician',
  'Actor',
  'Sports Person',
  'Fitness Trainer',
  'Yoga Instructor',
  'Homemaker',
  'Not Working',
  'Student',
  'Retired',
  'Freelancer',
  'Consultant',
  'Other',
].map((v) => ({ id: v, name: v }));

export const incomeRanges = [
  'Below 3 Lakhs',
  '3-5 Lakhs',
  '5-7 Lakhs',
  '7-10 Lakhs',
  '10-15 Lakhs',
  '15-20 Lakhs',
  '20-30 Lakhs',
  '30-40 Lakhs',
  '40-50 Lakhs',
  '50-60 Lakhs',
  '60-70 Lakhs',
  '70-80 Lakhs',
  '80-90 Lakhs',
  '90-100 Lakhs',
  '1 Crore+',
].map((v) => ({ id: v, name: v }));
